package itson.ticketwizard.presentacion;
import itson.ticketwizard.control.ControlCompra;
import itson.ticketwizard.entidades.Boleto;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.table.DefaultTableModel;

/**
 * @author García López, Yuri Germán - ID: 00000252583
 * @author Mendoza Baypoli, Vladimir Iván - ID: 00000252758
 * @author Romo López, Manuel - ID: 00000253080
 */

public class ConsultaBoletosEventoSeleccionado extends javax.swing.JFrame {

    private final ControlCompra control;
    private Integer codigoEvento;
    private JCheckBox[] arregloCheckBoxes;
 
    public ConsultaBoletosEventoSeleccionado(ControlCompra control, Integer codigoEvento) {
        initComponents();
        setIconImage(iconoPropio);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Consulta de boletos");
        this.control = control;
        this.codigoEvento = codigoEvento;
    }
    
    public void llenarTablaBoletos(Integer codigoEvento){

        List<Boleto> listaBoletos = this.control.obtenerBoletos(codigoEvento);
        DefaultTableModel modelo = (DefaultTableModel)this.tablaBoletosDisponibles.getModel();
        modelo.setRowCount(0);
        
        for(Boleto boleto: listaBoletos){
            Object[] filaTabla = {
                boleto.getNumeroSerie(),
                boleto.getFila(),
                boleto.getAsiento()
            };
            
            modelo.addRow(filaTabla);

        }
        
        arregloCheckBoxes = new JCheckBox[listaBoletos.size()];
        for(int i  = 0; i < arregloCheckBoxes.length; i++){
            arregloCheckBoxes[i] = new JCheckBox();
        }
        
    }

    public void llenarTablaBoletosReventa(Integer codigoEvento){
        List<Boleto> listaBoletos = this.control.obtenerBoletosReventa(codigoEvento);
        DefaultTableModel modelo = (DefaultTableModel)this.tablaBoletosDisponibles.getModel();
        modelo.setRowCount(0);
        for(Boleto boleto: listaBoletos){
            Object[] filaTabla = {
                boleto.getNumeroSerie(),
                boleto.getFila(),
                boleto.getAsiento()
            };
            modelo.addRow(filaTabla); 
        }
        
        arregloCheckBoxes = new JCheckBox[listaBoletos.size()];
        for(int i  = 0; i < arregloCheckBoxes.length; i++){
            arregloCheckBoxes[i] = new JCheckBox();
        }
    }
    
    public void llenarTablaBoletosBoletera(Integer codigoEvento){
        List<Boleto> listaBoletos = this.control.obtenerBoletosBoletera(codigoEvento);
        DefaultTableModel modelo = (DefaultTableModel)this.tablaBoletosDisponibles.getModel();
        modelo.setRowCount(0);
        for(Boleto boleto: listaBoletos){
            Object[] filaTabla = {
                boleto.getNumeroSerie(),
                boleto.getFila(),
                boleto.getAsiento()
            };
            modelo.addRow(filaTabla); 
        }
        
        arregloCheckBoxes = new JCheckBox[listaBoletos.size()];
        for(int i  = 0; i < arregloCheckBoxes.length; i++){
            arregloCheckBoxes[i] = new JCheckBox();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlPrincipal = new javax.swing.JPanel();
        panelEncabezado = new javax.swing.JPanel();
        etqLogo = new javax.swing.JLabel();
        etqTitulo = new javax.swing.JLabel();
        etqNombreUsuario = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();
        scrollBoletos = new javax.swing.JScrollPane();
        tablaBoletosDisponibles = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnRevender = new javax.swing.JButton();
        etqBoletosDe = new javax.swing.JLabel();
        etqNombreEvento = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicketWizard");

        pnlPrincipal.setBackground(new java.awt.Color(45, 48, 89));

        panelEncabezado.setBackground(new java.awt.Color(90, 137, 255));

        etqLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoTicketwizard.png"))); // NOI18N

        etqTitulo.setText("Ticketwizard");
        etqTitulo.setBackground(new java.awt.Color(255, 255, 255));
        etqTitulo.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        etqTitulo.setForeground(new java.awt.Color(255, 255, 255));

        etqNombreUsuario.setText("Nombre de Usuario");
        etqNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etqNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoUsuario.png"))); // NOI18N
        btnUsuario.setBackground(null);
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setToolTipText("");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(etqLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etqTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etqNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuario)
                .addGap(23, 23, 23))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etqTitulo)
                            .addComponent(etqNombreUsuario)))
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUsuario)
                            .addComponent(etqLogo))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        scrollBoletos.setBackground(new java.awt.Color(204, 204, 255));
        scrollBoletos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        scrollBoletos.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollBoletos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tablaBoletosDisponibles.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tablaBoletosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Serie", "Fila", "Asiento", "Selección de boleto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollBoletos.setViewportView(tablaBoletosDisponibles);

        btnVolver.setBackground(new java.awt.Color(192, 223, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnRevender.setBackground(new java.awt.Color(192, 223, 255));
        btnRevender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRevender.setText("Revender");
        btnRevender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenderActionPerformed(evt);
            }
        });

        etqBoletosDe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etqBoletosDe.setForeground(new java.awt.Color(255, 255, 255));
        etqBoletosDe.setText("Boletos de:");

        etqNombreEvento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etqNombreEvento.setForeground(new java.awt.Color(255, 255, 255));
        etqNombreEvento.setText("\"Nombre evento\"");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(126, 126, 126)
                .addComponent(btnRevender)
                .addGap(407, 407, 407))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(scrollBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(etqBoletosDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etqNombreEvento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqBoletosDe)
                    .addComponent(etqNombreEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(scrollBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRevender)
                    .addComponent(btnVolver))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        //Control para volver a la pantalla anterior
    }//GEN-LAST:event_btnVolverActionPerformed
        
    private void btnRevenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenderActionPerformed
        //Falta agregar action para revender
        
        
    }//GEN-LAST:event_btnRevenderActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRevender;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etqBoletosDe;
    private javax.swing.JLabel etqLogo;
    private javax.swing.JLabel etqNombreEvento;
    private javax.swing.JLabel etqNombreUsuario;
    private javax.swing.JLabel etqTitulo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane scrollBoletos;
    private javax.swing.JTable tablaBoletosDisponibles;
    // End of variables declaration//GEN-END:variables
    
    Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logoTicketwizard.png")).getScaledInstance(80, 80, Image.SCALE_SMOOTH);

}