package itson.ticketwizard.presentacion;
import itson.ticketwizard.control.ControlCompra;
import itson.ticketwizard.dtos.BoletosElegidosDTO;
import itson.ticketwizard.entidades.Boleto;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.table.DefaultTableModel;

/**
 * @author García López, Yuri Germán - ID: 00000252583
 * @author Mendoza Baypoli, Vladimir Iván - ID: 00000252758
 * @author Romo López, Manuel - ID: 00000253080
 */

public class DisponibilidadBoletos extends javax.swing.JFrame {

    private final ControlCompra control;
    private Integer codigoEvento;
    private JCheckBox[] arregloCheckBoxes;
 
    public DisponibilidadBoletos(ControlCompra control, Integer codigoEvento) {
        initComponents();
        this.control = control;
        this.codigoEvento = codigoEvento;
    }
    
    public void llenarTablaBoletos(Integer codigoEvento){

        List<Boleto> listaBoletos = this.control.obtenerBoletos(codigoEvento);
        DefaultTableModel modelo = (DefaultTableModel)this.tablaBoletosDisponibles.getModel();
        modelo.setRowCount(0);
        
        for(Boleto boleto: listaBoletos){
            Object[] filaTabla = {
                boleto.getNumeroSerie(),
                boleto.getFila(),
                boleto.getAsiento()
            };
            
            modelo.addRow(filaTabla);

        }
        
        arregloCheckBoxes = new JCheckBox[listaBoletos.size()];
        for(int i  = 0; i < arregloCheckBoxes.length; i++){
            arregloCheckBoxes[i] = new JCheckBox();
        }
        
    }

    public void llenarTablaBoletosReventa(Integer codigoEvento){
        List<Boleto> listaBoletos = this.control.obtenerBoletosReventa(codigoEvento);
        DefaultTableModel modelo = (DefaultTableModel)this.tablaBoletosDisponibles.getModel();
        modelo.setRowCount(0);
        for(Boleto boleto: listaBoletos){
            Object[] filaTabla = {
                boleto.getNumeroSerie(),
                boleto.getFila(),
                boleto.getAsiento()
            };
            modelo.addRow(filaTabla); 
        }
        
        arregloCheckBoxes = new JCheckBox[listaBoletos.size()];
        for(int i  = 0; i < arregloCheckBoxes.length; i++){
            arregloCheckBoxes[i] = new JCheckBox();
        }
    }
    
    public void llenarTablaBoletosBoletera(Integer codigoEvento){
        List<Boleto> listaBoletos = this.control.obtenerBoletosBoletera(codigoEvento);
        DefaultTableModel modelo = (DefaultTableModel)this.tablaBoletosDisponibles.getModel();
        modelo.setRowCount(0);
        for(Boleto boleto: listaBoletos){
            Object[] filaTabla = {
                boleto.getNumeroSerie(),
                boleto.getFila(),
                boleto.getAsiento()
            };
            modelo.addRow(filaTabla); 
        }
        
        arregloCheckBoxes = new JCheckBox[listaBoletos.size()];
        for(int i  = 0; i < arregloCheckBoxes.length; i++){
            arregloCheckBoxes[i] = new JCheckBox();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelEncabezado = new javax.swing.JPanel();
        etqLogo = new javax.swing.JLabel();
        etqTitulo = new javax.swing.JLabel();
        etqNombreUsuario = new javax.swing.JLabel();
        scrollBoletos = new javax.swing.JScrollPane();
        tablaBoletosDisponibles = new javax.swing.JTable();
        btnComprar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        radioBoletera = new javax.swing.JRadioButton();
        radioReventa = new javax.swing.JRadioButton();
        radioTodos = new javax.swing.JRadioButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicketWizard");

        panelEncabezado.setBackground(new java.awt.Color(0, 0, 153));

        etqLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoTicketwizard.png"))); // NOI18N

        etqTitulo.setText("Ticketwizard");
        etqTitulo.setBackground(new java.awt.Color(255, 255, 255));
        etqTitulo.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        etqTitulo.setForeground(new java.awt.Color(255, 255, 255));

        etqNombreUsuario.setText("Nombre de Usuario");
        etqNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etqNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(etqLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etqNombreUsuario)
                .addGap(94, 94, 94))
            .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEncabezadoLayout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(etqTitulo)
                    .addContainerGap(833, Short.MAX_VALUE)))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etqLogo))
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(etqNombreUsuario)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEncabezadoLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(etqTitulo)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        scrollBoletos.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollBoletos.setBackground(new java.awt.Color(204, 204, 255));
        scrollBoletos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tablaBoletosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Serie", "Fila", "Asiento", "Selección de boleto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollBoletos.setViewportView(tablaBoletosDisponibles);

        btnComprar.setText("Comprar");
        btnComprar.setBackground(new java.awt.Color(204, 255, 204));
        btnComprar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.setBackground(new java.awt.Color(204, 255, 204));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBoletera);
        radioBoletera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioBoletera.setText("De boletera");
        radioBoletera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoleteraActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioReventa);
        radioReventa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioReventa.setText("Reventa");
        radioReventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioReventaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioTodos);
        radioTodos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioTodos.setText("Todos");
        radioTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(scrollBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(radioReventa)
                        .addGap(18, 18, 18)
                        .addComponent(radioBoletera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioTodos)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioReventa)
                    .addComponent(radioBoletera)
                    .addComponent(radioTodos))
                .addGap(22, 22, 22)
                .addComponent(scrollBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioBoleteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoleteraActionPerformed
        this.llenarTablaBoletosBoletera(codigoEvento);
    }//GEN-LAST:event_radioBoleteraActionPerformed

    private void radioReventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioReventaActionPerformed
        this.llenarTablaBoletosReventa(codigoEvento);
    }//GEN-LAST:event_radioReventaActionPerformed

    private void radioTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTodosActionPerformed
        this.llenarTablaBoletos(codigoEvento);
    }//GEN-LAST:event_radioTodosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.control.volverEventosDisponibles(this);
    }//GEN-LAST:event_btnVolverActionPerformed
        
    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        
        
        BoletosElegidosDTO[] boletosElegidosDTO = new BoletosElegidosDTO[this.arregloCheckBoxes.length];
        
        
        for(int i  = 0; i < arregloCheckBoxes.length; i++){
             if (arregloCheckBoxes[i].isSelected()){
                 //Pendiente relacionar checkboxes con boletos seleccionados.
             }
        }
        
        
    }//GEN-LAST:event_btnComprarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etqLogo;
    private javax.swing.JLabel etqNombreUsuario;
    private javax.swing.JLabel etqTitulo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JRadioButton radioBoletera;
    private javax.swing.JRadioButton radioReventa;
    private javax.swing.JRadioButton radioTodos;
    private javax.swing.JScrollPane scrollBoletos;
    private javax.swing.JTable tablaBoletosDisponibles;
    // End of variables declaration//GEN-END:variables
}
