package itson.ticketwizard.presentacion;

import itson.ticketwizard.control.ControlIniciarSesion;

public class DisponibilidadDeBoletos extends javax.swing.JFrame {

    private final ControlIniciarSesion control;
    /**
     * Creates new form InicioSesionUsuario
     */
    public DisponibilidadDeBoletos(ControlIniciarSesion control) {
        initComponents();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jMenu1 = new javax.swing.JMenu();
        panelEncabezado = new javax.swing.JPanel();
        etqLogo = new javax.swing.JLabel();
        campoFechaInicial = new com.github.lgooddatepicker.components.DatePicker();
        campoFechaFinal = new com.github.lgooddatepicker.components.DatePicker();
        etqTitulo = new javax.swing.JLabel();
        etqFechaInicial = new javax.swing.JLabel();
        etqFechaFinal = new javax.swing.JLabel();
        campoBuscarEvento = new javax.swing.JTextField();
        etqBuscarEvento = new javax.swing.JLabel();
        etqNombreUsuario = new javax.swing.JLabel();
        panelEvento = new javax.swing.JPanel();
        btnEvento = new javax.swing.JButton();
        panelEvento2 = new javax.swing.JPanel();
        btnEvento1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicketWizard");

        panelEncabezado.setBackground(new java.awt.Color(0, 0, 153));

        etqLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoTicketwizard.png"))); // NOI18N

        etqTitulo.setText("Ticketwizard");
        etqTitulo.setBackground(new java.awt.Color(255, 255, 255));
        etqTitulo.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        etqTitulo.setForeground(new java.awt.Color(255, 255, 255));

        etqFechaInicial.setText("Fecha Inicial");
        etqFechaInicial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etqFechaInicial.setForeground(new java.awt.Color(255, 255, 255));

        etqFechaFinal.setText("Fecha Final");
        etqFechaFinal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etqFechaFinal.setForeground(new java.awt.Color(255, 255, 255));

        campoBuscarEvento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        etqBuscarEvento.setText("Buscar Evento");
        etqBuscarEvento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etqBuscarEvento.setForeground(new java.awt.Color(255, 255, 255));

        etqNombreUsuario.setText("Nombre de Usuario");
        etqNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etqNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addComponent(etqLogo)
                        .addGap(776, 776, 776)
                        .addComponent(etqNombreUsuario))
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addComponent(etqFechaInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etqFechaFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etqBuscarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBuscarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEncabezadoLayout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(etqTitulo)
                    .addContainerGap(833, Short.MAX_VALUE)))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etqLogo))
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(etqNombreUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqFechaInicial)
                    .addComponent(etqFechaFinal)
                    .addComponent(campoBuscarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqBuscarEvento))
                .addGap(37, 37, 37))
            .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEncabezadoLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(etqTitulo)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );

        panelEvento.setBackground(new java.awt.Color(51, 51, 51));

        btnEvento.setText("jButton1");
        btnEvento.setBackground(new java.awt.Color(102, 153, 255));
        btnEvento.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelEventoLayout = new javax.swing.GroupLayout(panelEvento);
        panelEvento.setLayout(panelEventoLayout);
        panelEventoLayout.setHorizontalGroup(
            panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEventoLayout.createSequentialGroup()
                .addGap(0, 994, Short.MAX_VALUE)
                .addComponent(btnEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelEventoLayout.setVerticalGroup(
            panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );

        panelEvento2.setBackground(new java.awt.Color(51, 51, 51));

        btnEvento1.setText("jButton1");
        btnEvento1.setBackground(new java.awt.Color(102, 153, 255));
        btnEvento1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelEvento2Layout = new javax.swing.GroupLayout(panelEvento2);
        panelEvento2.setLayout(panelEvento2Layout);
        panelEvento2Layout.setHorizontalGroup(
            panelEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEvento2Layout.createSequentialGroup()
                .addComponent(btnEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelEvento2Layout.setVerticalGroup(
            panelEvento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEvento1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEvento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(panelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(panelEvento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 106, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvento;
    private javax.swing.JButton btnEvento1;
    private javax.swing.JTextField campoBuscarEvento;
    private com.github.lgooddatepicker.components.DatePicker campoFechaFinal;
    private com.github.lgooddatepicker.components.DatePicker campoFechaInicial;
    private javax.swing.JLabel etqBuscarEvento;
    private javax.swing.JLabel etqFechaFinal;
    private javax.swing.JLabel etqFechaInicial;
    private javax.swing.JLabel etqLogo;
    private javax.swing.JLabel etqNombreUsuario;
    private javax.swing.JLabel etqTitulo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelEvento;
    private javax.swing.JPanel panelEvento2;
    // End of variables declaration//GEN-END:variables
}
