package itson.ticketwizard.presentacion;

import itson.ticketwizard.control.ControlIniciarSesion;
import itson.ticketwizard.dtos.NuevoUsuarioDTO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 * @author romom
 */
public class IngresoDatosRegistro extends javax.swing.JFrame {

    private final ControlIniciarSesion control;
    /**
     * Creates new form RegistroDatosInicioSesion
     */
    public IngresoDatosRegistro(ControlIniciarSesion control) {
        initComponents();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEncabezado = new javax.swing.JPanel();
        etqTitulo = new javax.swing.JLabel();
        etqLogo = new javax.swing.JLabel();
        panelIngresoDatos = new javax.swing.JPanel();
        etqIngresoDatos = new javax.swing.JLabel();
        etqNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        etqApellidoPaterno = new javax.swing.JLabel();
        campoApellidoPaterno = new javax.swing.JTextField();
        etqApellidoMaterno = new javax.swing.JLabel();
        campoApellidoMaterno = new javax.swing.JTextField();
        etqFechaNacimiento = new javax.swing.JLabel();
        campoFechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        etqDatosDeUbicacion = new javax.swing.JLabel();
        etqCalle = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        etqCiudad = new javax.swing.JLabel();
        campoCiudad = new javax.swing.JTextField();
        etqEstado = new javax.swing.JLabel();
        campoColonia = new javax.swing.JTextField();
        etqColonia = new javax.swing.JLabel();
        campoCalle = new javax.swing.JTextField();
        etqNúmero = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        campoCorreoElectronico = new javax.swing.JTextField();
        labelCorreoElectronico = new javax.swing.JLabel();
        etqContrasenia = new javax.swing.JLabel();
        campoContrasenia = new javax.swing.JPasswordField();
        btnVolver = new javax.swing.JButton();
        btnGuardarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelEncabezado.setBackground(new java.awt.Color(0, 0, 153));

        etqTitulo.setText("Ticketwizard");
        etqTitulo.setBackground(new java.awt.Color(255, 255, 255));
        etqTitulo.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        etqTitulo.setForeground(new java.awt.Color(255, 255, 255));

        etqLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoTicketwizard.png"))); // NOI18N

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(etqLogo)
                .addGap(305, 305, 305)
                .addComponent(etqTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addGroup(panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(etqTitulo))
                    .addGroup(panelEncabezadoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(etqLogo)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelIngresoDatos.setBackground(new java.awt.Color(255, 255, 255));

        etqIngresoDatos.setText("Ingrese sus datos");
        etqIngresoDatos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        etqNombre.setText("Nombre(s):");

        etqApellidoPaterno.setText("Apellido paterno:");

        etqApellidoMaterno.setText("Apellido materno:");

        etqFechaNacimiento.setText("Fecha de nacimiento:");

        etqDatosDeUbicacion.setText("Datos de ubicación");
        etqDatosDeUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        etqCalle.setText("Calle:");

        etqCiudad.setText("Ciudad:");

        etqEstado.setText("Estado:");

        etqColonia.setText("Colonia:");

        etqNúmero.setText("Número:");

        labelCorreoElectronico.setText("Correo electrónico:");

        etqContrasenia.setText("Contraseña:");

        javax.swing.GroupLayout panelIngresoDatosLayout = new javax.swing.GroupLayout(panelIngresoDatos);
        panelIngresoDatos.setLayout(panelIngresoDatosLayout);
        panelIngresoDatosLayout.setHorizontalGroup(
            panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresoDatosLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIngresoDatosLayout.createSequentialGroup()
                        .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etqNombre)
                            .addComponent(etqFechaNacimiento)
                            .addComponent(etqApellidoMaterno)
                            .addComponent(etqApellidoPaterno)
                            .addComponent(labelCorreoElectronico)
                            .addComponent(etqContrasenia))
                        .addGap(18, 18, 18)
                        .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombre)
                            .addComponent(campoApellidoPaterno)
                            .addComponent(campoApellidoMaterno)
                            .addComponent(campoFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(campoCorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(campoContrasenia)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIngresoDatosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etqCiudad)
                            .addComponent(etqColonia)
                            .addComponent(etqEstado))
                        .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIngresoDatosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelIngresoDatosLayout.createSequentialGroup()
                                        .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(etqCalle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelIngresoDatosLayout.createSequentialGroup()
                                        .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(campoCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                            .addComponent(campoColonia))
                                        .addGap(18, 18, 18)
                                        .addComponent(etqNúmero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoNumero))))
                            .addGroup(panelIngresoDatosLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(etqDatosDeUbicacion)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresoDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etqIngresoDatos)
                .addGap(160, 160, 160))
        );
        panelIngresoDatosLayout.setVerticalGroup(
            panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresoDatosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(etqIngresoDatos)
                .addGap(18, 18, 18)
                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCorreoElectronico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqApellidoPaterno))
                .addGap(8, 8, 8)
                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqApellidoMaterno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqFechaNacimiento)
                    .addComponent(campoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqContrasenia)
                    .addComponent(campoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(etqDatosDeUbicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etqCalle))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etqEstado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqNúmero)
                    .addComponent(etqCiudad))
                .addGap(7, 7, 7)
                .addGroup(panelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqColonia))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnGuardarDatos.setText("Guardar datos");
        btnGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(btnVolver)
                .addGap(49, 49, 49)
                .addComponent(btnGuardarDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(panelIngresoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(panelIngresoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnGuardarDatos))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDatosActionPerformed
        
        String nombres = this.campoNombre.getText();
        String apellidoPaterno = this.campoApellidoPaterno.getText();
        String apellidoMaterno = this.campoApellidoMaterno.getText();
        String correoElectronico = this.campoCorreoElectronico.getText();
        String fechaNacimiento = this.campoFechaNacimiento.getDateStringOrEmptyString();
        char[] contrasenia = this.campoContrasenia.getPassword();
        
        String contraseniaString = "";
        for(char c: contrasenia){
            contraseniaString += c;
        }
        
        String estado = this.campoEstado.getText();
        String ciudad = this.campoCiudad.getText();
        String colonia = this.campoColonia.getText();
        String calle = this.campoCalle.getText();
        Integer numero = Integer.valueOf(this.campoNumero.getText());
        
        NuevoUsuarioDTO nuevoUsuarioDTO = new NuevoUsuarioDTO(nombres, apellidoPaterno, apellidoMaterno, 
                correoElectronico, fechaNacimiento, contraseniaString, estado, ciudad, colonia, calle, numero);
        
        this.control.validarUsuario(nuevoUsuarioDTO);
    }//GEN-LAST:event_btnGuardarDatosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.control.volverPantallaIniciarSesion(this);
    }//GEN-LAST:event_btnVolverActionPerformed

    public void mostrarMensajeUsuarioExistente(){
        JOptionPane.showMessageDialog(this, "El usuario" + this.campoCorreoElectronico + "ya está en uso", "Usuario inválido", JOptionPane.INFORMATION_MESSAGE);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarDatos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField campoApellidoMaterno;
    private javax.swing.JTextField campoApellidoPaterno;
    private javax.swing.JTextField campoCalle;
    private javax.swing.JTextField campoCiudad;
    private javax.swing.JTextField campoColonia;
    private javax.swing.JPasswordField campoContrasenia;
    private javax.swing.JTextField campoCorreoElectronico;
    private javax.swing.JTextField campoEstado;
    private com.github.lgooddatepicker.components.DatePicker campoFechaNacimiento;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JLabel etqApellidoMaterno;
    private javax.swing.JLabel etqApellidoPaterno;
    private javax.swing.JLabel etqCalle;
    private javax.swing.JLabel etqCiudad;
    private javax.swing.JLabel etqColonia;
    private javax.swing.JLabel etqContrasenia;
    private javax.swing.JLabel etqDatosDeUbicacion;
    private javax.swing.JLabel etqEstado;
    private javax.swing.JLabel etqFechaNacimiento;
    private javax.swing.JLabel etqIngresoDatos;
    private javax.swing.JLabel etqLogo;
    private javax.swing.JLabel etqNombre;
    private javax.swing.JLabel etqNúmero;
    private javax.swing.JLabel etqTitulo;
    private javax.swing.JLabel labelCorreoElectronico;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelIngresoDatos;
    // End of variables declaration//GEN-END:variables
}
